name: Hugo preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: "latest"

      - name: Setup base URL env var
        run: |
          export PRNUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH") 
          echo BASEURL="https://nodeg-knowledge-build_preview-pr-"$PRNUMBER".surge.sh/" >> $GITHUB_ENV

      - name: Report base URL env var
        run: echo "${{ env.BASEURL }}"

      - name: Build
        run: hugo --baseURL "${{ env.BASEURL }}"

      - name: Deploy to surge
        uses: afc163/surge-preview@v1
        id: preview_step
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: public
          failOnError: false
          teardown: true
          build: |
            echo Deploying to surge.sh
